# Generated by Django 4.2.5 on 2023-10-01 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.TextField()),
                ('phone', models.CharField(max_length=16, verbose_name='Телефон участника экскурсии')),
            ],
        ),
    ]
