# Generated by Django 4.2.5 on 2023-09-30 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_alter_tour_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='slots_str',
            field=models.TextField(blank=True, null=True),
        ),
    ]
