# Generated by Django 4.2.5 on 2023-09-30 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_tour_slots_str'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='main_image',
            field=models.ImageField(null=True, default=None, upload_to='', verbose_name='tours'),
            preserve_default=False,
        ),
    ]
