# Generated by Django 4.2.5 on 2023-09-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_tour_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Название экскурсии'),
        ),
    ]
