# Generated by Django 4.2.5 on 2023-09-30 08:56

from django.db import migrations, models
import django.db.models.deletion
import tours.models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_alter_tour_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='main_image',
            field=models.ImageField(null=True, upload_to=tours.models.get_tour_main_image_path),
        ),
        migrations.CreateModel(
            name='TourImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=tours.models.get_tour_images_path)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.tour')),
            ],
        ),
    ]
