# Generated by Django 4.2.5 on 2023-09-30 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_alter_tour_main_image_tourimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourimage',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tours.tour'),
        ),
    ]
