# Generated by Django 4.2.5 on 2023-10-01 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('tours', '0010_tour_max_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='start_location',
        ),
        migrations.AddField(
            model_name='schedule',
            name='participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.participant'),
        ),
    ]
